from datetime import datetime
from typing import Protocol

from models.ai import AIProviderConfig, AIReport


class IAIProviderRepository(Protocol):
    async def list_all(self) -> list[AIProviderConfig]: ...
    async def get(self, key: str) -> AIProviderConfig | None: ...
    async def upsert(self, provider: AIProviderConfig) -> AIProviderConfig: ...
    async def delete(self, key: str) -> bool: ...


class IAIReportRepository(Protocol):
    async def create(self, report: AIReport) -> AIReport: ...
    async def list_recent(self, *, offset: int, limit: int) -> list[AIReport]: ...
    async def count(self) -> int: ...
    async def get_latest(self, kind: str | None = None) -> AIReport | None: ...
    async def sum_tokens_since(self, since: datetime) -> tuple[int, int]: ...
