from datetime import datetime
from typing import Protocol

from models.antispam import AntiSpamEvent, AntiSpamEventType


class IAntiSpamRepository(Protocol):
    async def create(self, event: AntiSpamEvent) -> AntiSpamEvent: ...
    async def count_total_warnings(self) -> int: ...
    async def count_total_blocks(self) -> int: ...
    async def count_today(self, today_start: datetime) -> int: ...
    async def count_last_7_days(self, seven_days_ago: datetime) -> int: ...
    async def count_last_30_days(self, thirty_days_ago: datetime) -> int: ...