from datetime import datetime
from typing import Protocol

from models.broadcast import BroadcastRecord


class IBroadcastRepository(Protocol):
    async def create(self, record: BroadcastRecord) -> BroadcastRecord: ...
    async def get_latest(self) -> BroadcastRecord | None: ...
    async def count_total(self) -> int: ...
    async def count_today(self, today_start: datetime) -> int: ...
    async def count_last_7_days(self, seven_days_ago: datetime) -> int: ...
    async def count_last_30_days(self, thirty_days_ago: datetime) -> int: ...