from typing import Protocol

from models.force_subscription import ForceSubscriptionTarget


class IForceSubscriptionRepository(Protocol):
    async def get(self, chat_id: int) -> ForceSubscriptionTarget | None: ...
    async def list_active(self) -> list[ForceSubscriptionTarget]: ...
    async def list_all(self) -> list[ForceSubscriptionTarget]: ...
    async def create(self, target: ForceSubscriptionTarget) -> ForceSubscriptionTarget: ...
    async def update(self, target: ForceSubscriptionTarget) -> ForceSubscriptionTarget: ...
    async def delete(self, chat_id: int) -> bool: ...
