from datetime import datetime
from typing import Protocol

from models.force_subscription_event import ForceSubscriptionMembershipEvent


class IForceSubscriptionEventRepository(Protocol):
    async def create(
        self, event: ForceSubscriptionMembershipEvent
    ) -> ForceSubscriptionMembershipEvent: ...

    async def count_total(self) -> int: ...
    async def count_since(self, since: datetime) -> int: ...
    async def count_target_total(self, target_chat_id: int) -> int: ...
    async def count_target_since(self, target_chat_id: int, since: datetime) -> int: ...
