from datetime import datetime
from typing import Protocol

from models.referral_reward import ReferralRewardEntry, ReferralRewardHistoryItem


class IReferralRewardRepository(Protocol):
    async def create(self, entry: ReferralRewardEntry) -> ReferralRewardEntry: ...
    async def sum_invites_consumed(self, referrer_id: int) -> int: ...
    async def sum_coins(self, referrer_id: int) -> int: ...
    async def sum_coins_total(self) -> int: ...
    async def count_total(self) -> int: ...
    async def count_since(self, since: datetime) -> int: ...
    async def list_recent(self, *, limit: int) -> list[ReferralRewardEntry]: ...
    async def list_recent_with_names(
        self, *, limit: int
    ) -> list[ReferralRewardHistoryItem]: ...
