from datetime import datetime
from typing import Protocol

from models.user import User


class IReferralRepository(Protocol):
    async def get_referral_code(self, telegram_id: int) -> str | None: ...
    async def set_referral_code_if_missing(self, telegram_id: int, code: str) -> bool: ...
    async def find_user_by_referral_code(self, code: str) -> User | None: ...
    async def claim_referral(
        self, telegram_id: int, referrer_id: int, processed_at: datetime
    ) -> bool: ...
    async def mark_referral_processed(
        self, telegram_id: int, processed_at: datetime
    ) -> bool: ...
    async def count_referrals(self, telegram_id: int) -> int: ...
    async def list_referrals(
        self, telegram_id: int, *, offset: int, limit: int
    ) -> list[User]: ...
    async def count_referrals_total(self) -> int: ...
    async def count_referred_registered(self) -> int: ...
    async def count_users_with_referral_code(self) -> int: ...
    async def count_referrals_since(self, since: datetime) -> int: ...
    async def top_referrers(self, *, limit: int) -> list[tuple[User, int]]: ...
