from datetime import datetime
from typing import Protocol

from models.support import SupportStatus, SupportTicket, SupportUserSummary


class ISupportRepository(Protocol):
    async def create(self, ticket: SupportTicket) -> SupportTicket: ...
    async def get_by_id(self, ticket_id: int) -> SupportTicket | None: ...
    async def list_by_user(self, telegram_id: int) -> list[SupportTicket]: ...
    async def list_by_user_and_status(self, telegram_id: int, status: SupportStatus) -> list[SupportTicket]: ...
    async def list_by_status(self, status: SupportStatus) -> list[SupportTicket]: ...
    async def list_user_summaries_by_status(self, status: SupportStatus) -> list[SupportUserSummary]: ...
    async def update(self, ticket: SupportTicket) -> SupportTicket | None: ...
    async def update_user_status(self, telegram_id: int, status: SupportStatus) -> int: ...
    async def delete_by_status(self, status: SupportStatus) -> int: ...
    async def delete_all(self) -> int: ...

    # Statistics
    async def count_total(self) -> int: ...
    async def count_by_status(self, status: SupportStatus) -> int: ...
    async def count_today(self, today_start: datetime) -> int: ...
    async def count_last_7_days(self, seven_days_ago: datetime) -> int: ...
    async def count_last_30_days(self, thirty_days_ago: datetime) -> int: ...
