from typing import Protocol

from models.support import SupportStatus, SupportTicket, SupportUserSummary


class ISupportRepository(Protocol):
    async def create(self, ticket: SupportTicket) -> SupportTicket: ...
    async def get_by_id(self, ticket_id: int) -> SupportTicket | None: ...
    async def list_by_user(self, telegram_id: int) -> list[SupportTicket]: ...
    async def list_by_user_and_status(self, telegram_id: int, status: SupportStatus) -> list[SupportTicket]: ...
    async def list_by_status(self, status: SupportStatus) -> list[SupportTicket]: ...
    async def list_user_summaries_by_status(self, status: SupportStatus) -> list[SupportUserSummary]: ...
    async def update(self, ticket: SupportTicket) -> SupportTicket | None: ...
    async def update_user_status(self, telegram_id: int, status: SupportStatus) -> int: ...
