from typing import Protocol

from models.user import User


class IUserRepository(Protocol):
    async def exists(self, telegram_id: int) -> bool: ...
    async def create(self, user: User) -> User: ...
    async def get_by_telegram_id(self, telegram_id: int) -> User | None: ...
    async def update(self, user: User) -> User | None: ...
    async def delete(self, telegram_id: int) -> bool: ...
    async def list_all(self) -> list[User]: ...
    async def list_page(self, *, offset: int, limit: int) -> list[User]: ...
    async def count(self) -> int: ...
    async def count_registered(self) -> int: ...
    async def count_unregistered(self) -> int: ...
    async def list_active_telegram_ids(self, *, registered_only: bool = False) -> list[int]: ...
    async def list_blocked_page(self, *, offset: int, limit: int) -> list[User]: ...
    async def count_blocked(self) -> int: ...
    async def count_active(self) -> int: ...
    async def count_active_today(self, today_start: datetime) -> int: ...
    async def count_active_last_7_days(self, seven_days_ago: datetime) -> int: ...
    async def count_inactive_30_days(self, thirty_days_ago: datetime) -> int: ...
    async def count_active(self) -> int: ...
    async def count_active_today(self) -> int: ...
    async def count_active_last_7_days(self) -> int: ...
    async def count_inactive_30_days(self) -> int: ...
